services:
  - type: web
    name: medicare
    runtime: python
    buildCommand: >
      export PATH="/opt/render/project/poetry/bin:$PATH" &&
      pip install poetry &&
      poetry install &&
      poetry run python manage.py collectstatic --no-input &&
      poetry run python manage.py migrate
    startCommand: poetry run gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: medicare-db
    databaseName: medicare
    plan: free