services:
  - type: web
    name: medicare
    runtime: python
    rootDir: .
    buildCommand: >
      cd /opt/render/project/src &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate
    startCommand: cd /opt/render/project/src && gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: medicare-db
    databaseName: medicare
    plan: free