services:
  - type: web
    name: medicare
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: medicare-db
    databaseName: medicare
    plan: free